# Generated by Django 3.1.4 on 2020-12-20 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('cast', models.TextField()),
                ('season', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-movie_type'],
            },
        ),
        migrations.CreateModel(
            name='MovieType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='')),
                ('video', models.FileField(upload_to='')),
                ('media_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.mediatype')),
            ],
            options={
                'verbose_name_plural': 'Videos',
                'ordering': ['-media_type'],
            },
        ),
        migrations.AddField(
            model_name='mediatype',
            name='movie_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movietype'),
        ),
    ]
